version: "3"

services:

  redis:
    container_name: redis
    image: redis:6.2.5
    ports:
      - "6379:6379"

  zookeeper:
    container_name: zookeeper
    image: bitnami/zookeeper:3.9.1
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    container_name: kafka
    image: bitnami/kafka:3.5.1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: INTERNAL://kafka:9093,EXTERNAL://localhost:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9093,EXTERNAL://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

  fake_twitter:
    container_name: fake_twitter
    build:
      context: ./backend/simulated_data/fake_twitter/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  tweet_producer:
    container_name: tweet_producer
    build:
      context: ./backend/stream/tweet_producer/
      dockerfile: Dockerfile
    depends_on:
      - kafka
      - fake_twitter
    env_file:
      - .env

  flink_consumer:
    container_name: flink_consumer
    build:
      context: ./backend/stream/flink_consumer/
      dockerfile: Dockerfile
    depends_on:
      - kafka
      - redis
    env_file:
      - .env

  streamlit:
    container_name: streamlit
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - redis
    env_file:
      - .env

